
name: linkseq

channels:
  - bioconda
  - defaults
  - AgBiome

# NOTE: conda-forge is needed for multiqc v1.8, but in some bizarre way, conda-forge breaks my Nextflow
# installation, such that processes are not submitted in parallel properly.

dependencies:
  - nextflow=20.01.0
  - ema=0.6.2
  - bwa=0.7.17
  - samtools=1.9
  - bbtools=37.62
  - gatk4=4.1.0.0
  - r-gsalib=2.1
  - r-gplots=3.0.1.1
  - r-ggplot2=3.1.1
  - bxtools=0.1.0
  - hapcut2=1.2
  - whatshap=0.18
  - qualimap=2.2.2a
  #- multiqc=1.8
  - snpeff=4.3.1t
